(() => {
  'use strict';
  const config = window.QUIZ_CONFIG;
  const root = document.querySelector('#quiz');
  const routeNames = ['inicio','objetivo','corpo','areas','resultados','altura','peso','meta','processamento','aprovado'];
  const base = {age:null,goal:null,body:null,areas:[],height:175,weight:75,target:70};
  let answers = {...base};
  try { const saved=JSON.parse(sessionStorage.getItem('militar-quiz') || 'null'); if(saved && typeof saved==='object') answers={...base,...saved,areas:Array.isArray(saved.areas)?saved.areas:[]}; } catch {}
  let page=0, busy=false, disposers=[], previousProgress=0;
  const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
  const asset = name => `assets/${name}.webp`;
  const save = () => {try{sessionStorage.setItem('militar-quiz',JSON.stringify(answers))}catch{}};
  const cleanup = () => { disposers.forEach(fn=>fn());disposers=[]; };
  const later = (fn,ms) => {const id=setTimeout(fn,ms);disposers.push(()=>clearTimeout(id));return id};
  const image = (name,cls='') => `<img class="${cls}" src="${asset(name)}" alt="" draggable="false">`;
  const button = (label='CONTINUAR',disabled=false) => `<button class="primary next" ${disabled?'disabled':''}>${label} <span aria-hidden="true">→</span></button>`;
  const back = () => `<button class="back" type="button"><span aria-hidden="true">‹</span>ANTERIOR</button>`;
  const controls=(next=true,disabled=false)=>`<div class="controls">${next?button('CONTINUAR',disabled):''}${back()}</div>`;
  function questionHeader(n){return `<header class="question-head"><div class="eyebrow">CUESTIONARIO</div><div class="question-line"><b>PREGUNTA ${String(n).padStart(2,'0')}</b><span class="percent">${Math.round(n/9*100)}%</span></div><div class="progress" role="progressbar" aria-label="Progreso del cuestionario" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${Math.round(n/9*100)}"><i style="--progress:${previousProgress}%" data-target="${n/9*100}"></i></div></header>`}
  function cards(group,labels,key,multi=false){return `<div class="choices ${['goal','areas'].includes(group)?'icon-choices':''}" role="group" aria-label="Opciones">${labels.map((text,i)=>`<button class="choice ${(multi?answers[key].includes(i):answers[key]===i)?'selected':''}" type="button" data-index="${i}" aria-pressed="${multi?answers[key].includes(i):answers[key]===i}">${image(config.images[group][i])}<span class="label">${text}</span></button>`).join('')}</div>`}
  function navigate(n){if(busy)return;busy=true;cleanup();save();const screen=root.querySelector('.screen');screen?.classList.add('leaving');setTimeout(()=>{location.hash=routeNames[n];if(page===n)render(n)},reduced?0:170)}
  function choices(key,multi=false){root.querySelectorAll('.choice').forEach(b=>b.addEventListener('click',()=>{if(busy)return;const i=+b.dataset.index;if(multi){answers[key]=answers[key].includes(i)?answers[key].filter(n=>n!==i):[...answers[key],i];b.classList.toggle('selected');b.setAttribute('aria-pressed',String(answers[key].includes(i)));root.querySelector('.next').disabled=!answers[key].length;save()}else{answers[key]=i;save();root.querySelectorAll('.choice').forEach(c=>{c.classList.toggle('selected',c===b);c.setAttribute('aria-pressed',String(c===b))});busy=true;later(()=>{busy=false;navigate(page+1)},240)}}))}
  function carousel(){let index=0;const track=root.querySelector('.slides'),region=root.querySelector('.carousel');const dots=[...root.querySelectorAll('.dot')];let interval;function show(i){index=(i+config.results.length)%config.results.length;track.style.transform=`translateX(-${index*100}%)`;dots.forEach((d,j)=>{d.classList.toggle('active',j===index);d.setAttribute('aria-pressed',String(j===index))});root.querySelectorAll('.slide').forEach((s,j)=>s.setAttribute('aria-hidden',String(j!==index)))}function start(){clearInterval(interval);if(!reduced)interval=setInterval(()=>{if(!document.hidden&&!region.matches(':hover')&&!region.contains(document.activeElement))show(index+1)},config.carouselInterval)}dots.forEach((d,i)=>d.addEventListener('click',()=>{show(i);start()}));let x=0;region.addEventListener('touchstart',e=>{x=e.touches[0].clientX;clearInterval(interval)},{passive:true});region.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-x;if(Math.abs(dx)>30)show(index+(dx<0?1:-1));start()},{passive:true});show(0);start();disposers.push(()=>clearInterval(interval))}
  function resultMarkup(){return `<section class="screen results enter"><span class="tag">● RESULTADOS VERIFICADOS</span><h1 class="screen-title" tabindex="-1">ESTO VA A PASARTE A TI</h1><p class="subtitle">Transformaciones reales en 21 Días siguiendo el Protocolo Calistenia Militar</p><div class="carousel" aria-label="Resultados antes y después" aria-roledescription="carrusel"><div class="slides">${config.results.map((r,i)=>`<article class="slide montage-slide" aria-label="${i+1} de ${config.results.length}" aria-roledescription="diapositiva"><div class="montage-space"><div class="montage-frame" style="--zoom:${r.zoom}"><img src="${asset(r.id)}" alt="${r.name}: antes y después en una sola imagen" draggable="false"></div></div><div class="identity"><b>${r.name}</b>, <span>${r.age} AÑOS</span></div><div class="result-copy"><h3>${r.title}</h3><p>${r.text}</p>${r.illustrative?'<small class="profile-note">Perfil y texto ilustrativos</small>':''}</div><div class="seal">RESULTADOS INDIVIDUALES PUEDEN VARIAR</div></article>`).join('')}</div></div><div class="carousel-nav" aria-label="Elegir resultado">${config.results.map((r,i)=>`<button class="dot" aria-label="Mostrar resultado de ${r.name}" aria-pressed="${i===0}"></button>`).join('')}</div>${controls()}</section>`}
  function rulerMarkup(number,title,key,unit,min,max){return `<section class="screen ruler-screen enter">${questionHeader(number)}<div class="title-block"><h1 class="screen-title" tabindex="-1">${title}</h1></div><div class="measure-content"><div class="measurement"><output id="measure-value">${answers[key]}</output><span class="unit">${unit}</span></div><div class="ruler" role="slider" tabindex="0" aria-label="${title}" aria-valuemin="${min}" aria-valuemax="${max}" aria-valuenow="${answers[key]}" aria-valuetext="${answers[key]} ${unit}" data-key="${key}" data-min="${min}" data-max="${max}"><div class="ticks">${Array.from({length:max-min+1},(_,i)=>{const n=min+i;return `<span class="tick ${n%10===0?'major':''}" style="left:${n*8}px">${n%10===0?`<label>${n}</label>`:''}</span>`}).join('')}</div><span class="needle"></span></div><p class="drag-hint">ARRASTRE PARA AJUSTAR</p></div>${controls()}</section>`}
  function ruler(){const el=root.querySelector('.ruler'),key=el.dataset.key,min=+el.dataset.min,max=+el.dataset.max;let startX=0,startValue=0,dragging=false;const unit=key==='height'?'CM':'KG';function set(v){v=Math.max(min,Math.min(max,Math.round(v)));answers[key]=v;el.setAttribute('aria-valuenow',v);el.setAttribute('aria-valuetext',`${v} ${unit}`);root.querySelector('#measure-value').textContent=v;el.querySelector('.ticks').style.transform=`translateX(${-v*8}px)`;save()}el.addEventListener('pointerdown',e=>{if(e.button!==0)return;dragging=true;startX=e.clientX;startValue=answers[key];el.setPointerCapture(e.pointerId);el.focus({preventScroll:true})});el.addEventListener('pointermove',e=>{if(dragging)set(startValue+(startX-e.clientX)/8)});const stop=()=>{dragging=false};el.addEventListener('pointerup',stop);el.addEventListener('pointercancel',stop);el.addEventListener('lostpointercapture',stop);el.addEventListener('keydown',e=>{const keys={ArrowRight:1,ArrowUp:1,ArrowLeft:-1,ArrowDown:-1,PageUp:10,PageDown:-10};if(e.key in keys){e.preventDefault();set(answers[key]+keys[e.key])}else if(e.key==='Home'||e.key==='End'){e.preventDefault();set(e.key==='Home'?min:max)}});set(answers[key])}
  function processingMarkup(){return `<section class="screen processing enter"><div class="processing-panel"><header><span class="tag">♦ PROTOCOLO: 2026</span><h1 tabindex="-1">PROCESANDO<br>RECLUTAMIENTO</h1><p class="subtitle">Verificando compatibilidad operativa...</p></header><div><div class="processing-label"><span>ESTADO: ANALIZANDO</span><b id="loading-percent">0%</b></div><div class="progress" role="progressbar" aria-label="Preparando protocolo" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><i style="--progress:0%"></i></div></div><ol class="processing-steps">${['ANALIZANDO PERFIL TÁCTICO','GENERANDO PROTOCOLO MILITAR','PREPARANDO TU MISIÓN DE 21 DÍAS','FINALIZANDO TU RECLUTAMIENTO'].map((s,i)=>`<li class="process-step" data-icon="${['◎','◉','▦','♧'][i]}"><span class="process-icon" aria-hidden="true">${['◎','◉','▦','♧'][i]}</span><div><strong>${s}</strong><small>&gt; Ejecutando secuencia...</small></div></li>`).join('')}</ol><footer class="secure">SISTEMA SEGURO // ACCESO LIMITADO</footer></div><p class="sr-only" role="status" id="process-status">Preparando tu protocolo</p></section>`}
  function process(){const start=performance.now(),duration=config.processingDuration,steps=[...root.querySelectorAll('.process-step')];let raf,lastStep=-1;function tick(now){const t=Math.min(1,(now-start)/duration),active=Math.min(3,Math.floor(t*4)),pct=Math.round((1-Math.pow(1-t,2))*100);root.querySelector('#loading-percent').textContent=pct+'%';root.querySelector('.progress').setAttribute('aria-valuenow',pct);root.querySelector('.progress i').style.setProperty('--progress',pct+'%');steps.forEach((s,i)=>{s.classList.toggle('active',i===active&&t<1);s.classList.toggle('done',i<active||t===1);s.querySelector('.process-icon').textContent=(i<active||t===1)?'✓':s.dataset.icon});if(active!==lastStep){root.querySelector('#process-status').textContent=steps[active].querySelector('strong').textContent;lastStep=active}if(t<1)raf=requestAnimationFrame(tick);else later(()=>navigate(9),250)}raf=requestAnimationFrame(tick);disposers.push(()=>cancelAnimationFrame(raf))}
  function approvedMarkup(){return `<section class="screen approved enter"><div class="medal" aria-hidden="true">🎖️</div><h1 tabindex="-1">RECLUTA<em>APROBADO</em></h1><p class="subtitle">Tu perfil cumple con los requisitos para el<b>Protocolo de Fuerzas Especiales.</b></p><div class="report"><div class="report-head"><span>INFORME FINAL</span><span>ID: #8X-299</span></div><div class="report-item"><span class="report-icon">📋</span><div><h3>Protocolo Generado</h3><p>Plan de entrenamiento adaptado a tu biotipo y objetivos actuales.</p></div></div><div class="report-item"><span class="report-icon">🎥</span><div><h3>Acceso a Vídeos</h3><p>Biblioteca técnica con ejecución correcta de cada movimiento.</p></div></div><div class="report-item"><span class="report-icon">🔥</span><div><h3>Garantía de Resultados</h3><p>Método probado en campo con tasa de éxito del 98%.</p></div></div></div><a class="primary sales-link" href="${config.salesUrl}">ACCEDER AL PROTOCOLO <span aria-hidden="true">🔒</span></a></section>`}
  function render(n){cleanup();page=n;busy=false;document.documentElement.scrollTop=0;document.body.scrollTop=0;
    if(n===0)root.innerHTML=`<section class="screen age enter"><span class="tag">● RECLUTAMIENTO ABIERTO</span><h1 tabindex="-1">CONSIGUE UN FÍSICO MARCADO EN SOLO 21 DÍAS CON EL <em>DESAFÍO DE CALISTENIA MILITAR</em>SIN SALIR DE CASA.</h1><p class="subtitle">Este programa está diseñado para adaptarse a tu nivel de condición física y edad actual.</p><p class="prompt">Selecciona tu edad para comenzar</p>${cards('age',['Edad: 18 - 29','Edad: 30 - 39','Edad: 40 - 49','Edad: 50+'],'age')}</section>`;
    if(n===1)root.innerHTML=`<section class="screen enter">${questionHeader(2)}<div class="title-block"><h1 class="screen-title" tabindex="-1">¿Cuál es tu objetivo principal?</h1></div>${cards('goal',['Perder peso','Ganar músculo','Perder grasa y ganar músculo','Mejorar la condición física general'],'goal')}${controls(false)}</section>`;
    if(n===2)root.innerHTML=`<section class="screen enter">${questionHeader(3)}<div class="title-block"><h1 class="screen-title" tabindex="-1">¿Cuál es tu objetivo corporal?</h1></div>${cards('body',['Delgado','Atlético','Marcado','Fuerte'],'body')}${controls(false)}</section>`;
    if(n===3)root.innerHTML=`<section class="screen enter">${questionHeader(4)}<div class="title-block"><h1 class="screen-title" tabindex="-1">¿Cuáles son las áreas en las que quieres enfocarte?</h1><p class="subtitle">Elige todas las opciones que apliquen.</p></div>${cards('areas',['Pectorales','Brazos','Abdomen','Piernas'],'areas',true)}${controls(true,!answers.areas.length)}</section>`;
    if(n===4)root.innerHTML=resultMarkup();
    if(n===5)root.innerHTML=rulerMarkup(7,'¿CUÁL ES TU ALTURA?','height','CM',120,220);
    if(n===6)root.innerHTML=rulerMarkup(8,'¿Cuál es tu peso actual?','weight','KG',35,200);
    if(n===7)root.innerHTML=rulerMarkup(9,'¿Cuál es el peso que quieres alcanzar?','target','KG',35,200);
    if(n===8)root.innerHTML=processingMarkup();
    if(n===9)root.innerHTML=approvedMarkup();
    root.querySelector('h1')?.focus({preventScroll:true});
    root.querySelector('.back')?.addEventListener('click',()=>navigate(Math.max(0,page-1)));
    root.querySelector('.next')?.addEventListener('click',()=>navigate(page+1));
    const progress=root.querySelector('[data-target]');if(progress){const target=+progress.dataset.target;requestAnimationFrame(()=>requestAnimationFrame(()=>progress.style.setProperty('--progress',target+'%')));previousProgress=target}
    if(n===0)choices('age');if(n===1)choices('goal');if(n===2)choices('body');if(n===3)choices('areas',true);if(n===4)carousel();if(n>=5&&n<=7)ruler();if(n===8)process();
  }
  function fromHash(){const route=location.hash.slice(1),idx=routeNames.indexOf(route);render(idx>=0?idx:0)}
  window.addEventListener('hashchange',fromHash);fromHash();
})();
